### ISSUE TITLE
Event under label may not exist

### ISSUE THREAD

**Issue by dustinbyrne** [applandinc/appmap-js#141]
See attached AppMap. Click into the `provider.http.cookie` label, select `ActionDispatch::Cookies::CookieJar#[]=` from the middle/bottom of the list.

[Microposts_interface_micropost_interface.appmap.json.txt](https://github.com/applandinc/appmap-js/files/6222874/Microposts_interface_micropost_interface.appmap.json.txt)

**Comment by sashahonchar** [comment]
Those events exist and they doesn't have `parent`, but by default in Trace view we show only HTTP events as roots:

https://github.com/applandinc/appmap-js/blob/e8e73bc44a31be08787b964a9f0493fabb459193/src/pages/VsCodeExtension.vue#L182

That's why events are available in the search panel list, but when you click on "View in Trace" they are not shown.

**Comment by kgilpin** [comment]
Yes. So, if events are filtered out of the Trace, they should also be
filtered out of the search. And the user should have an option to disable
the automatic filter.
