### ISSUE TITLE
"View AppMaps" step exists in the quickstart webview.

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-js#278]
Figma mockup: https://www.figma.com/file/fqM92VioD2fKNkwcz5VYjO/user-milestones?node-id=711%3A8200

- [x] This step can only be navigated to after an appmap has already been recorded. 
- [x] Navigating to this step focuses the side view on the "Local files" section and expands it. 
- [x] This step does not get completed until user opens an AppMap 
- [x] The Webview should suggest a few (up to 5) good AppMaps to open

**Comment by ptrdvrk** [comment]
@Daniel-Warner-X @typaulhus what should happen after user completes this step? Should we show a "Quickstart completed!" message in the step or something similar? It might be useful for the user to return to this step to pick a few good AppMaps to open later, too.

**Comment by Daniel-Warner-X** [comment]
> @Daniel-Warner-X @typaulhus what should happen after user completes this step? Should we show a "Quickstart completed!" message in the step or something similar? It might be useful for the user to return to this step to pick a few good AppMaps to open later, too.

I added a line to the design that says 'You have completed the Quickstart.' This is a valuable addition because it informs the user as to the status of the system and their own progress. I removed 'for more information go here' because we really need the user to get to their first AppMap. It's a binary condition of success. Giving them the opportunity to bail from the happy path so close to the finish is a big liability. Lastly, I put the AppMap list into a table for better legibility, fewer extraneous words.

![image](https://user-images.githubusercontent.com/1229326/125354317-a836d300-e331-11eb-9f9a-04612e2461ea.png)
