### ISSUE TITLE
Diagrams filter out media requests for blacklisted file extensions

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-js#453]
See the attached AppMap as an example, 44 out of 41 requests are for images, css, .js files etc.:
[test.appmap.json.txt](https://github.com/applandinc/appmap-js/files/7523588/test.appmap.json.txt)
 

When the "Hide HTTP media requests" filter is on, all requests for these file extensions should be hidden:
- bitmap images (.jpg, .png, .jpeg, .gif, .ico, ...)
- vector images (.svg, ...)
- .css files
- .js files
- font files (.woff, .otf, .tff, ...)
- video files (.mp4, .mov, .flv, .avi, ...)
- .html files

**Comment by sashahonchar** [comment]
@dustinbyrne , @ptrdvrk  We already filtering out media requests:
https://github.com/applandinc/appmap-js/blob/main/packages/components/src/pages/VsCodeExtension.vue#L346-L371

Looks like events in provided AppMap weren't filtered because for some reason `mime_type` is empty:
![image](https://user-images.githubusercontent.com/1647695/141504598-d4ae136f-9361-4483-966e-52a119426132.png)

**Comment by kgilpin** [comment]
The web server isn’t providing a content type.

**Comment by sashahonchar** [comment]
Done  https://github.com/applandinc/appmap-js/pull/429/commits/11bcb3588928b3c72844b4391f5fe748d452148f
